### PR TITLE
Change screenshots images

### LINKED ISSUE #11: Update the screenshots of the app in readme
**Describe the chore**
Currently, the images in the readme are of the older version of the app. Updates the screenshots present in the readme.

**Additional Context**
Link of the screenshots to be added: https://photos.google.com/share/AF1QipOPqafBSDWt2ijQ91Fwd1o9O72fDLjhTaks3zg-xZ-7jRxXWd6Eep3evU6dNnjOHQ?key=T1RqSlJiMDlGbExSaURnaHVEbTlEWWxFaWhzMlFn

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

### PR DESCRIPTION
**Pull request by Anshul1507**
Fixes #11 

Changes: Replace all the readme images

Screenshots for the change:
<br>

### CODE REVIEW

**Comment by rob729** [comment]
@Anshul1507 Where is the screenshot of readme after making the changes?
You have added only the screenshot of the existing readme.

**Review by rob729 — COMMENTED** [review]
@Anshul1507 Where is the screenshot of readme after making the changes?
You have added only the screenshot of the existing readme.

**Comment by Anshul1507** [comment]
Screenshots for the change:
<br>

**Comment by rob729** [comment]
@Anshul1507 Why did you closed this PR?

**Comment by Anshul1507** [comment]
Actually there were more changes in readme file, so creating new PR

**Pull request closed without merging**
